import { Department, Category, Employee } from "./types";

export const initialDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Engineering",
    head: "Aditi Rao",
    parentDept: "--",
    status: "Active",
    employeesCount: 28,
  },
  {
    id: "dept-2",
    name: "Facilities",
    head: "Rohan Mehta",
    parentDept: "--",
    status: "Active",
    employeesCount: 6,
  },
  {
    id: "dept-3",
    name: "Field Ops",
    head: "Sana Iqbal",
    parentDept: "--",
    status: "Active",
    employeesCount: 14,
  },
  {
    id: "dept-4",
    name: "Field Ops (East)",
    head: "Sana Iqbal",
    parentDept: "Field Ops",
    status: "Inactive",
    employeesCount: 0,
  },
  {
    id: "dept-5",
    name: "Marketing",
    head: "John Doe",
    parentDept: "--",
    status: "Active",
    employeesCount: 8,
  },
  {
    id: "dept-6",
    name: "Finance",
    head: "Sarah Jenkins",
    parentDept: "--",
    status: "Active",
    employeesCount: 5,
  },
];

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    description: "Laptops, tablets, monitors, phone devices, and utility cameras.",
    assetsCount: 142,
    warrantyPeriod: 24,
    status: "Active",
  },
  {
    id: "cat-2",
    name: "Office Furniture",
    description: "Desks, ergonomic office chairs, tables, and cabinets.",
    assetsCount: 84,
    warrantyPeriod: 60,
    status: "Active",
  },
  {
    id: "cat-3",
    name: "IT Infrastructure",
    description: "Enterprise servers, networking hardware, routers, and switches.",
    assetsCount: 36,
    warrantyPeriod: 36,
    status: "Active",
  },
  {
    id: "cat-4",
    name: "Vehicles",
    description: "Company transport cars, logistics vans, and trucks.",
    assetsCount: 12,
    warrantyPeriod: 48,
    status: "Active",
  },
  {
    id: "cat-5",
    name: "Software Licenses",
    description: "SaaS software seats, premium keys, and enterprise subscriptions.",
    assetsCount: 50,
    warrantyPeriod: 0,
    status: "Inactive",
  },
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Aditi Rao",
    email: "aditi.rao@company.com",
    department: "Engineering",
    role: "VP of Engineering",
    status: "Active",
  },
  {
    id: "emp-2",
    name: "Rohan Mehta",
    email: "rohan.mehta@company.com",
    department: "Facilities",
    role: "Facilities Lead",
    status: "Active",
  },
  {
    id: "emp-3",
    name: "Sana Iqbal",
    email: "sana.iqbal@company.com",
    department: "Field Ops",
    role: "Field Ops Manager",
    status: "Active",
  },
  {
    id: "emp-4",
    name: "Arpit Patel",
    email: "arpit.patel@company.com",
    department: "Engineering",
    role: "Lead UI Developer",
    status: "Active",
  },
  {
    id: "emp-5",
    name: "Priya Sharma",
    email: "priya.sharma@company.com",
    department: "HR",
    role: "HR Administrator",
    status: "Active",
  },
  {
    id: "emp-6",
    name: "Alex Wong",
    email: "alex.wong@company.com",
    department: "Engineering",
    role: "Senior QA Analyst",
    status: "Inactive",
  },
];
