import { Asset } from "./types";

export const initialAssets: Asset[] = [
  {
    id: "asset-1",
    assetTag: "AF-0012",
    name: "Dell Latitude 5420",
    category: "Electronics",
    status: "Allocated",
    department: "Engineering",
    assignedTo: "Arpit Patel",
    location: "Bengaluru HQ",
    lastUpdated: "2026-07-10",
    condition: "New",
    serialNumber: "S/N: DL-9824041",
    purchaseDate: "2026-01-15",
    warrantyPeriod: 24,
    shared: false,
  },
  {
    id: "asset-2",
    assetTag: "AF-0062",
    name: "Epson Projector 4K",
    category: "Electronics",
    status: "Maintenance",
    department: "Facilities",
    assignedTo: "--",
    location: "HQ Floor 2",
    lastUpdated: "2026-07-09",
    condition: "Fair",
    serialNumber: "S/N: EP-1120421",
    purchaseDate: "2025-06-20",
    warrantyPeriod: 12,
    shared: true,
  },
  {
    id: "asset-3",
    assetTag: "AF-0201",
    name: "Ergonomic Office Chair",
    category: "Office Furniture",
    status: "Available",
    department: "HR",
    assignedTo: "--",
    location: "Warehouse A",
    lastUpdated: "2026-07-08",
    condition: "Good",
    serialNumber: "S/N: FR-8842012",
    purchaseDate: "2024-03-10",
    warrantyPeriod: 60,
    shared: false,
  },
  {
    id: "asset-4",
    assetTag: "AF-0015",
    name: "MacBook Pro 16\"",
    category: "Electronics",
    status: "Allocated",
    department: "Engineering",
    assignedTo: "Aditi Rao",
    location: "Bengaluru HQ",
    lastUpdated: "2026-07-11",
    condition: "New",
    serialNumber: "S/N: MB-4492019",
    purchaseDate: "2026-05-01",
    warrantyPeriod: 36,
    shared: false,
  },
  {
    id: "asset-5",
    assetTag: "AF-0220",
    name: "Conference Table 10-Seater",
    category: "Office Furniture",
    status: "Reserved",
    department: "Facilities",
    assignedTo: "--",
    location: "HQ Room 402",
    lastUpdated: "2026-07-05",
    condition: "Good",
    serialNumber: "S/N: FR-3320145",
    purchaseDate: "2025-02-12",
    warrantyPeriod: 48,
    shared: true,
  },
  {
    id: "asset-6",
    assetTag: "AF-0310",
    name: "Toyota Hiace Delivery Van",
    category: "Vehicles",
    status: "Available",
    department: "Field Ops",
    assignedTo: "--",
    location: "Logistics Yard 2",
    lastUpdated: "2026-07-07",
    condition: "Fair",
    serialNumber: "S/N: VH-9942004",
    purchaseDate: "2023-11-20",
    warrantyPeriod: 48,
    shared: true,
  },
  {
    id: "asset-7",
    assetTag: "AF-0044",
    name: "Canon EOS R5 Camera",
    category: "Electronics",
    status: "Lost",
    department: "Marketing",
    assignedTo: "John Doe",
    location: "--",
    lastUpdated: "2026-06-30",
    condition: "Poor",
    serialNumber: "S/N: CN-2200451",
    purchaseDate: "2025-01-10",
    warrantyPeriod: 24,
    shared: true,
  },
];
